### PR TITLE
Multi-arch release building

### PR DESCRIPTION
**Pull request by bshelton229**
Multi-arch building for checkbridge. This is part of the effort to get arm64 for everything.

### CODE REVIEW

**Comment by bshelton229** [comment]
Aaaaand, no idea why all these github checks are failing after changing a build script. I'll look into it.

**Comment by ascandella** [comment]
@bshelton229 I think the file you want to modify is the `codecov.yml` in this repo (https://github.com/roverdotcom/checkbridge/blob/master/codecov.yml). Try setting the `threshold` to something like `5%`: https://docs.codecov.io/docs/codecovyml-reference#coveragestatus

**Comment by bshelton229** [comment]
> @bshelton229 I think the file you want to modify is the `codecov.yml` in this repo (https://github.com/roverdotcom/checkbridge/blob/master/codecov.yml). Try setting the `threshold` to something like `5%`: https://docs.codecov.io/docs/codecovyml-reference#coveragestatus

Thanks @ascandella that worked great!

**Review by RafaelCapella — APPROVED** [review]
LGTM

**Pull request merged**
